dockarmaiiihc:
  image: thalhalla/dockarmaiii:${DOCKARMAIII_BRANCH}
  command: ${DOCKARMAIII_COMMAND}
  environment:
    STEAM_USERNAME: ${STEAM_USERNAME}
    STEAM_PASSWORD: ${STEAM_PASSWORD}
    STEAM_GID: 233780
    SERVER_IP: ${SERVER_IP}
    SERVER_PORT: ${SERVER_PORT}
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.sidekicks: dockarmaiii-datavolume
  volumes_from:
    - dockarmaiiihc-datavolume
dockarmaiiihc-datavolume:
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
  volume_driver: ${VOLUME_DRIVER}
  volumes:
    - ${VOLUME_NAME}:/home/steam
  image: thalhalla/dockarmaiii:${DOCKARMAIII_BRANCH}
  command: /bin/true
