.catalog:
  name: "dockarmaiiihc"
  version: "0.3.1"
  decription: A reliable ArmA3 Dedicated steam server
  questions:
      - variable: "STEAM_USERNAME"
        description: "Username from steam to use for the server"
        label: "Steam Username"
        required: true
        default: ""
        type: "string"
      - variable: "STEAM_PASSWORD"
        description: "Password from steam to use for the server"
        label: "Steam Password"
        required: true
        default: ""
        type: "password"
      - variable: "SERVER_IP"
        description: "The server IP to associate with this headless client"
        label: "Server IP"
        required: true
        default: "0.0.0.0"
        type: "string"
      - variable: "SERVER_PORT"
        description: "Server PORT to associate with this headless client"
        label: "Server port"
        required: true
        default: "2302"
        type: "string"
      - variable: "VOLUME_DRIVER"
        description: "The VOLUME driver to associate with this server (convoy-nfs,convoy-efs,convoy-ebs)"
        label: "Volume Driver"
        required: true
        default: "rancher-nfs"
        type: enum
        options: # List of options if using type of `enum`
          - rancher-nfs
          - rancher-efs
          - rancher-ebs
          - convoy-nfs
          - convoy-efs
          - convoy-ebs
      - variable: "VOLUME_NAME"
        description: "The VOLUME name to associate with this server"
        label: "Volume Name"
        required: true
        default: "ARMA3HC"
        type: "string"
      - variable: "DOCKARMAIII_COMMAND"
        description: "The command name to associate with this server"
        label: "command"
        required: true
        default: "/assets/headless.sh"
        type: "string"
      - variable: "DOCKARMAIII_BRANCH"
        description: "The command name to associate with this server"
        label: "BRANCH"
        required: true
        default: "latest"
        type: "string"
dockarmaiiihc:
  metadata:
    dockarmaiiihc:
      config:
       node.name: "$${HOSTNAME}"
