.catalog:
  name: Team Fortress 2 dedicated server
  version: "0.2.6-aws-chooser"
  description:  Team Fortress 2 dedicated server in a rancher server
  uuid: 0.1.1
  minimum_rancher_version: 0.1.1
  questions:
      - variable: "STEAM_USERNAME"
        description: "Username from steam to use for the server"
        label: "Steam Username"
        required: true
        default: "Anonymous"
        type: "string"
      - variable: "STEAM_PASSWORD"
        description: "Password from steam to use for the server"
        label: "Steam Password"
        required: false
        default: ""
        type: "password"
      - variable: "STEAM_GSLT"
        description: "The Steam Game Server Login Token (GSLT) from steam to use for the server [go here (use GID 440) -> http://steamcommunity.com/dev/managegameservers]"
        label: "Steam Game Server Login Token"
        required: true
        default: ""
        type: "password"
      - variable: "TF2_EXEC"
        description: "Which server config to execute from the cfg folder (e.g. server_competitive.cfg"
        label: "Server Config"
        required: true
        default: "server_competitive.cfg"
        type: "string"
      - variable: "TF2_MOTD_URL"
        description: "give an URL to your MOTD"
        label: "MOTD"
        required: true
        default: "https://raw.githubusercontent.com/Thalhalla/tf2/master/assets/motd.txt"
        type: "string"
      - variable: "TF2_PASSWORD"
        description: "Which server password for admin"
        label: "Admin password"
        required: true
        default: ""
        type: "string"
      - variable: "TF2_MAIL"
        description: "email address to associate with this server"
        label: "Email"
        required: true
        default: "admin@thalhalla.com"
        type: "string"
      - variable: "TF2_HOSTNAME"
        description: "Server name to associate with this server"
        label: "Servername"
        required: true
        default: "Thalhalla.com-rent-a-server"
        type: "string"
      - variable: "VOLUME_DRIVER"
        description: "The VOLUME driver to associate with this server (convoy-nfs,convoy-efs,convoy-ebs)"
        label: "VOLUME Driver"
        required: true
        default: "convoy-nfs"
        type: "string"
      - variable: "VOLUME_NAME"
        description: "The VOLUME name to associate with this server"
        label: "VOLUME Name"
        required: true
        default: "TF2"
        type: "string"
