name: Traefik-Thalhalla
description: |
  Traefik active load balancer with Thalhalla defaults
version: v1.2.3-rancher1-thalhall-4
category: Load Balancing
maintainer: "Josh Cox <josh@webhosting.coop>"
minimum_rancher_version: v0.59.0
license:
projectURL: https://github.com/rawmind0/alpine-traefik
