.catalog:
  name: "steamer"
  version: "0.1.0"
  decription: A reliable CS:GO steam server
  questions:
      - variable: "STEAM_USERNAME"
        description: "Username from steam to use for the server"
        label: "Steam Username"
        required: true
        default: "Anonymous"
        type: "string"
      - variable: "STEAM_PASSWORD"
        description: "Password from steam to use for the server"
        label: "Steam Password"
        required: true
        default: "xxxx"
        type: "string"
      - variable: "STEAM_GID"
        description: "App ID or GID from steam to use for the server"
        label: "Steam Game ID"
        required: true
        default: "440"
        type: "string"
      - variable: "STEAM_GSLT"
        description: "The Steam Game Server Login Token (GLST) from steam to use for the server [hint: go <a href=http://steamcommunity.com/dev/managegameservers>here</a> ]"
        label: "Steam Game Server Login Token"
        required: true
        default: "REPLACE_ME"
        type: "string"
      - variable: "TF2_EXEC"
        description: "Which server config to execute from the cfg folder (e.g. server_competitive.cfg"
        label: "Server Config"
        required: true
        default: "server_competitive.cfg"
        type: "string"
      - variable: "PORT"
        description: "PORT to associate with this server)"
        label: "PORT"
        required: true
        default: "27015"
        type: "string"
      - variable: "CS_GAME_TYPE"
        description: "Which CS:GO server game type to execute"
        label: "Game Type"
        required: true
        default: "1"
        type: "string"
      - variable: "CS_GAME_MODE"
        description: "Which CS:GO server game mode to execute"
        label: "Game Mode"
        required: true
        default: "1"
        type: "string"
      - variable: "CS_MAP_GROUP"
        description: "Which CS:GO server map group to execute"
        label: "Map Group"
        required: true
        default: "1"
        type: "string"
      - variable: "CS_INITIAL_MAP"
        description: "Which CS:GO server map group to execute"
        label: "Initial Map"
        required: true
        default: "1"
        type: "string"
steamer:
  metadata:
    steamer:
      config:
       node.name: "$${HOSTNAME}"
