.catalog:
  name: "steamer"
  version: "0.3.1"
  decription: A reliable CS-GO steam server
  questions:
      - variable: "STEAM_USERNAME"
        description: "Username from steam to use for the server"
        label: "Steam Username"
        required: true
        default: "anonymous"
        type: "string"
      - variable: "STEAM_PASSWORD"
        description: "Password from steam to use for the server"
        label: "Steam Password"
        required: false
        default: ""
        type: "string"
      - variable: "STEAM_GSLT"
        description: "The Steam Game Server Login Token (GLST) from steam to use for the server [hint: go here (use GID 730) -> http://steamcommunity.com/dev/managegameservers ]"
        label: "Steam Game Server Login Token"
        required: true
        default: ""
        type: "string"
      - variable: "CS_EXEC"
        description: "Which server config to execute from the cfg folder "
        label: "Server Config"
        required: true
        default: "gamemode_cooperative.cfg"
        type: "string"
      - variable: "CS_GAME_TYPE"
        description: "Which CS-GO server game type to execute"
        label: "Game Type"
        required: true
        default: "1"
        type: "string"
      - variable: "CS_GAME_MODE"
        description: "Which CS-GO server game mode to execute"
        label: "Game Mode"
        required: true
        default: "1"
        type: "string"
      - variable: "CS_MAP_GROUP"
        description: "Which CS-GO server map group to execute"
        label: "Map Group"
        required: true
        default: "mg_demolition"
        type: "string"
      - variable: "CS_INITIAL_MAP"
        description: "Which CS-GO server map initially to execute"
        label: "Initial Map"
        required: true
        default: "de_lake"
        type: "string"
      - variable: "VOLUME_DRIVER"
        description: "The VOLUME driver to associate with this server (convoy-nfs,convoy-efs,convoy-ebs)"
        label: "VOLUME Driver"
        required: true
        default: "convoy-nfs"
        type: "string"
      - variable: "VOLUME_NAME"
        description: "The VOLUME name to associate with this server"
        label: "VOLUME Name"
        required: true
        default: "CSGO"
        type: "string"
      - variable: "host_label"
        description: "Host label where to run this service."
        label: "Host label:"
        required: true
        default: "public=true"
        type: "string"
steamer:
  metadata:
    steamer:
      config:
       node.name: "$${HOSTNAME}"
