dockarmaiii:
  image: thalhalla/dockarmaiii:${DOCKARMAIII_BRANCH}
  command: ${DOCKARMAIII_COMMAND}
  environment:
    STEAM_USERNAME: ${STEAM_USERNAME}
    STEAM_PASSWORD: ${STEAM_PASSWORD}
    STEAM_GID: 233780
    IP: ${IP}
    PORT: ${PORT}
    PORT2: ${PORT2}
    PORT3: ${PORT3}
    PORT4: ${PORT4}
    CLIENT_IP: 10.42.227.26
    CLIENT_IP2: 10.42.227.25
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.requested_ip: 10.42.227.27
    io.rancher.sidekicks: dockarmaiii-datavolume
  volumes_from:
    - dockarmaiii-datavolume
  ports:
    - "${PORT}:${PORT}/udp"
    - "2303:2303/udp"
    - "2304:2304/udp"
    - "2305:2305/udp"
dockarmaiiihc1:
  image: thalhalla/dockarmaiii:${DOCKARMAIII_BRANCH}
  command: /assets/headless.sh
  environment:
    STEAM_USERNAME: ${STEAM_USERNAME}
    STEAM_PASSWORD: ${STEAM_PASSWORD}
    STEAM_GID: 233780
    IP: ${IP}
    PORT: ${PORT}
    PORT2: ${PORT2}
    PORT3: ${PORT3}
    PORT4: ${PORT4}
    SERVER_IP: 10.42.227.27
  labels:
    io.rancher.container.requested_ip: 10.42.227.26
    io.rancher.sidekicks: dockarmaiii-datavolume
  volumes_from:
    - dockarmaiii-datavolume
dockarmaiii-datavolume:
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
  volume_driver: ${VOLUME_DRIVER}
  volumes:
    - ${VOLUME_NAME}:/home/steam
  image: thalhalla/dockarmaiii:${DOCKARMAIII_BRANCH}
  command: /bin/true
